export const CITIES_OF_JATIM = [
  { id: 0, name: "SEMUA KOTA", code: "0", province_code: 0, label: "SEMUA KOTA", value: "SEMUA KOTA" },
  {
    id: 228,
    code: "35.01",
    name: "PACITAN",
    label: "PACITAN",
    value: "PACITAN",
    province_code: 35,
  },
  {
    id: 229,
    code: "35.02",
    name: "PONOROGO",
    label: "PONOROGO",
    value: "PONOROGO",
    province_code: 35,
  },
  {
    id: 230,
    code: "35.03",
    name: "TRENGGALEK",
    label: "TRENGGALEK",
    value: "TRENGGALEK",
    province_code: 35,
  },
  {
    id: 231,
    code: "35.04",
    name: "TULUNGAGUNG",
    label: "TULUNGAGUNG",
    value: "TULUNGAGUNG",
    province_code: 35,
  },
  {
    id: 232,
    code: "35.05",
    name: "BLITAR",
    label: "BLITAR",
    value: "BLITAR",
    province_code: 35,
  },
  {
    id: 234,
    code: "35.07",
    name: "MALANG",
    label: "MALANG",
    value: "MALANG",
    province_code: 35,
  },
  {
    id: 235,
    code: "35.08",
    name: "LUMAJANG",
    label: "LUMAJANG",
    value: "LUMAJANG",
    province_code: 35,
  },
  {
    id: 236,
    code: "35.09",
    name: "JEMBER",
    label: "JEMBER",
    value: "JEMBER",
    province_code: 35,
  },
  {
    id: 238,
    code: "35.11",
    name: "BONDOWOSO",
    label: "BONDOWOSO",
    value: "BONDOWOSO",
    province_code: 35,
  },
  {
    id: 239,
    code: "35.12",
    name: "SITUBONDO",
    label: "SITUBONDO",
    value: "SITUBONDO",
    province_code: 35,
  },
  {
    id: 240,
    code: "35.13",
    name: "PROBOLINGGO",
    label: "PROBOLINGGO",
    value: "PROBOLINGGO",
    province_code: 35,
  },
  {
    id: 241,
    code: "35.14",
    name: "PASURUAN",
    label: "PASURUAN",
    value: "PASURUAN",
    province_code: 35,
  },
  {
    id: 243,
    code: "35.16",
    name: "MOJOKERTO",
    label: "MOJOKERTO",
    value: "MOJOKERTO",
    province_code: 35,
  },
  {
    id: 244,
    code: "35.17",
    name: "JOMBANG",
    label: "JOMBANG",
    value: "JOMBANG",
    province_code: 35,
  },
  {
    id: 245,
    code: "35.18",
    name: "NGANJUK",
    label: "NGANJUK",
    value: "NGANJUK",
    province_code: 35,
  },
  {
    id: 246,
    code: "35.19",
    name: "MADIUN",
    label: "MADIUN",
    value: "MADIUN",
    province_code: 35,
  },
  {
    id: 248,
    code: "35.21",
    name: "NGAWI",
    label: "NGAWI",
    value: "NGAWI",
    province_code: 35,
  },
  {
    id: 249,
    code: "35.22",
    name: "BOJONEGORO",
    label: "BOJONEGORO",
    value: "BOJONEGORO",
    province_code: 35,
  },
  {
    id: 250,
    code: "35.23",
    name: "TUBAN",
    label: "TUBAN",
    value: "TUBAN",
    province_code: 35,
  },
  {
    id: 252,
    code: "35.25",
    name: "GRESIK",
    label: "GRESIK",
    value: "GRESIK",
    province_code: 35,
  },
  {
    id: 253,
    code: "35.26",
    name: "BANGKALAN",
    label: "BANGKALAN",
    value: "BANGKALAN",
    province_code: 35,
  },
  {
    id: 254,
    code: "35.27",
    name: "SAMPANG",
    label: "SAMPANG",
    value: "SAMPANG",
    province_code: 35,
  },
  {
    id: 255,
    code: "35.28",
    name: "PAMEKASAN",
    label: "PAMEKASAN",
    value: "PAMEKASAN",
    province_code: 35,
  },
  {
    id: 257,
    code: "35.71",
    name: "KOTA KEDIRI",
    label: "KOTA KEDIRI",
    value: "KOTA KEDIRI",
    province_code: 35,
  },
  {
    id: 258,
    code: "35.72",
    name: "KOTA BLITAR",
    label: "KOTA BLITAR",
    value: "KOTA BLITAR",
    province_code: 35,
  },
  {
    id: 259,
    code: "35.73",
    name: "KOTA MALANG",
    label: "KOTA MALANG",
    value: "KOTA MALANG",
    province_code: 35,
  },
  {
    id: 261,
    code: "35.75",
    name: "KOTA PASURUAN",
    label: "KOTA PASURUAN",
    value: "KOTA PASURUAN",
    province_code: 35,
  },
  {
    id: 262,
    code: "35.76",
    name: "KOTA MOJOKERTO",
    label: "KOTA MOJOKERTO",
    value: "KOTA MOJOKERTO",
    province_code: 35,
  },
  {
    id: 263,
    code: "35.77",
    name: "KOTA MADIUN",
    label: "KOTA MADIUN",
    value: "KOTA MADIUN",
    province_code: 35,
  },
  {
    id: 264,
    code: "35.78",
    name: "KOTA SURABAYA",
    label: "KOTA SURABAYA",
    value: "KOTA SURABAYA",
    province_code: 35,
  },
  {
    id: 233,
    code: "35.06",
    name: "KEDIRI",
    label: "KEDIRI",
    value: "KEDIRI",
    province_code: 35,
  },
  {
    id: 237,
    code: "35.10",
    name: "BANYUWANGI",
    label: "BANYUWANGI",
    value: "BANYUWANGI",
    province_code: 35,
  },
  {
    id: 242,
    code: "35.15",
    name: "SIDOARJO",
    label: "SIDOARJO",
    value: "SIDOARJO",
    province_code: 35,
  },
  {
    id: 247,
    code: "35.20",
    name: "MAGETAN",
    label: "MAGETAN",
    value: "MAGETAN",
    province_code: 35,
  },
  {
    id: 251,
    code: "35.24",
    name: "LAMONGAN",
    label: "LAMONGAN",
    value: "LAMONGAN",
    province_code: 35,
  },
  {
    id: 256,
    code: "35.29",
    name: "SUMENEP",
    label: "SUMENEP",
    value: "SUMENEP",
    province_code: 35,
  },
  {
    id: 260,
    code: "35.74",
    name: "KOTA PROBOLINGGO",
    label: "KOTA PROBOLINGGO",
    value: "KOTA PROBOLINGGO",
    province_code: 35,
  },
  {
    id: 265,
    code: "35.79",
    name: "KOTA BATU",
    label: "KOTA BATU",
    value: "KOTA BATU",
    province_code: 35,
  },
];
