export const CITIES_OF_SUMUT = [
  { id: 315, name: "SEMUA KOTA", code: "0", province_code: 0, label: "SEMUA KOTA", value: "SEMUA KOTA" },
  {
    id: 24,
    code: "12.01",
    name: "TAPANULI TENGAH",
    label: "TAPANULI TENGAH",
    value: "TAPANULI TENGAH",
    province_code: 12,
  },
  {
    id: 25,
    code: "12.02",
    name: "TAPANULI UTARA",
    label: "TAPANULI UTARA",
    value: "TAPANULI UTARA",
    province_code: 12,
  },
  { id: 27, code: "12.04", name: "NIAS", label: "NIAS", value: "NIAS", province_code: 12 },
  { id: 28, code: "12.05", name: "LANGKAT", label: "LANGKAT", value: "LANGKAT", province_code: 12 },
  { id: 29, code: "12.06", name: "KARO", label: "KARO", value: "KARO", province_code: 12 },
  { id: 30, code: "12.07", name: "DELI SERDANG", label: "DELI SERDANG", value: "DELI SERDANG", province_code: 12 },
  { id: 31, code: "12.08", name: "SIMALUNGUN", label: "SIMALUNGUN", value: "SIMALUNGUN", province_code: 12 },
  { id: 33, code: "12.1", name: "LABUHANBATU", label: "LABUHANBATU", value: "LABUHANBATU", province_code: 12 },
  { id: 34, code: "12.11", name: "DAIRI", label: "DAIRI", value: "DAIRI", province_code: 12 },
  { id: 35, code: "12.12", name: "TOBA SAMOSIR", label: "TOBA SAMOSIR", value: "TOBA SAMOSIR", province_code: 12 },
  { id: 37, code: "12.14", name: "NIAS SELATAN", label: "NIAS SELATAN", value: "NIAS SELATAN", province_code: 12 },
  { id: 38, code: "12.15", name: "PAKPAK BHARAT", label: "PAKPAK BHARAT", value: "PAKPAK BHARAT", province_code: 12 },
  {
    id: 39,
    code: "12.16",
    name: "HUMBANG HASUNDUTAN",
    label: "HUMBANG HASUNDUTAN",
    value: "HUMBANG HASUNDUTAN",
    province_code: 12,
  },
  { id: 40, code: "12.17", name: "SAMOSIR", label: "SAMOSIR", value: "SAMOSIR", province_code: 12 },
  { id: 42, code: "12.19", name: "BATU BARA", label: "BATU BARA", value: "BATU BARA", province_code: 12 },
  {
    id: 43,
    code: "12.2",
    name: "PADANG LAWAS UTARA",
    label: "PADANG LAWAS UTARA",
    value: "PADANG LAWAS UTARA",
    province_code: 12,
  },
  { id: 44, code: "12.21", name: "PADANG LAWAS", label: "PADANG LAWAS", value: "PADANG LAWAS", province_code: 12 },
  {
    id: 45,
    code: "12.22",
    name: "LABUHANBATU SELATAN",
    label: "LABUHANBATU SELATAN",
    value: "LABUHANBATU SELATAN",
    province_code: 12,
  },
  { id: 47, code: "12.24", name: "NIAS UTARA", label: "NIAS UTARA", value: "NIAS UTARA", province_code: 12 },
  { id: 48, code: "12.25", name: "NIAS BARAT", label: "NIAS BARAT", value: "NIAS BARAT", province_code: 12 },
  { id: 49, code: "12.71", name: "KOTA MEDAN", label: "KOTA MEDAN", value: "KOTA MEDAN", province_code: 12 },
  {
    id: 50,
    code: "12.72",
    name: "KOTA PEMATANG SIANTAR",
    label: "KOTA PEMATANG SIANTAR",
    value: "KOTA PEMATANG SIANTAR",
    province_code: 12,
  },
  {
    id: 52,
    code: "12.74",
    name: "KOTA TANJUNG BALAI",
    label: "KOTA TANJUNG BALAI",
    value: "KOTA TANJUNG BALAI",
    province_code: 12,
  },
  { id: 53, code: "12.75", name: "KOTA BINJAI", label: "KOTA BINJAI", value: "KOTA BINJAI", province_code: 12 },
  {
    id: 54,
    code: "12.76",
    name: "KOTA TEBING TINGGI",
    label: "KOTA TEBING TINGGI",
    value: "KOTA TEBING TINGGI",
    province_code: 12,
  },
  {
    id: 55,
    code: "12.77",
    name: "KOTA PADANGSIDIMPUAN",
    label: "KOTA PADANGSIDIMPUAN",
    value: "KOTA PADANGSIDIMPUAN",
    province_code: 12,
  },
  {
    id: 26,
    code: "12.03",
    name: "TAPANULI SELATAN",
    label: "TAPANULI SELATAN",
    value: "TAPANULI SELATAN",
    province_code: 12,
  },
  { id: 32, code: "12.09", name: "ASAHAN", label: "ASAHAN", value: "ASAHAN", province_code: 12 },
  {
    id: 36,
    code: "12.13",
    name: "MANDAILING NATAL",
    label: "MANDAILING NATAL",
    value: "MANDAILING NATAL",
    province_code: 12,
  },
  {
    id: 41,
    code: "12.18",
    name: "SERDANG BEDAGAI",
    label: "SERDANG BEDAGAI",
    value: "SERDANG BEDAGAI",
    province_code: 12,
  },
  {
    id: 46,
    code: "12.23",
    name: "LABUHANBATU UTARA",
    label: "LABUHANBATU UTARA",
    value: "LABUHANBATU UTARA",
    province_code: 12,
  },
  { id: 51, code: "12.73", name: "KOTA SIBOLGA", label: "KOTA SIBOLGA", value: "KOTA SIBOLGA", province_code: 12 },
  {
    id: 56,
    code: "12.78",
    name: "KOTA GUNUNGSITOLI",
    label: "KOTA GUNUNGSITOLI",
    value: "KOTA GUNUNGSITOLI",
    province_code: 12,
  },
];
